title : TE4201
author: 'aruba-te@hpe.com - Confidential - For training purposes only'
copyright: '2024 Hewlett Packard Enterprise Development LP'
logo: 'images/hpe-logo.png'

description: >-
 TE4201 Lab Guide

execute:
  execute_notebooks           : off

html:
  home_page_in_navbar         : true
  favicon                     : 'images/fav-icon-32.png'